AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.fisinter.card::aws-card
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.fisinter.card.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AwsUserApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/card/api/v1'
    Export:
      Name: AwsCardApi
