CREATE TABLE administradores (
    ID_ADMIN INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PERFIL ENUM('Superadministrador','Administrador') NOT NULL,
    ID_EMPRESA INT,
    TELEFONO VARCHAR(20),
    DIRECCION TEXT,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_EMPRESA) REFERENCES empresas(ID_EMPRESA)
); 