-- Crear la tabla empresas con la estructura correcta
CREATE TABLE IF NOT EXISTS empresas (
    ID_EMPRESA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_EMPRESA VARCHAR(255) NOT NULL,
    MONTO_MAXIMO DECIMAL(10,2) DEFAULT 0.00,
    NUMERO_TARJETAS INT DEFAULT 0,
    ESTATUS ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 