-- Crear la base de datos
CREATE DATABASE IF NOT EXISTS adminfinister;
USE adminfinister;

-- Crear tabla de usuarios (si no existe)
CREATE TABLE IF NOT EXISTS usuarios (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Crear tabla de tarjetas
CREATE TABLE IF NOT EXISTS tarjetas (
    ID_TARJETA INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    NUMERO_TARJETA VARCHAR(16) NOT NULL,
    PIN VARCHAR(4) NOT NULL,
    FECHA_ASIGNACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS ENUM('ACTIVA', 'INACTIVA', 'BLOQUEADA') DEFAULT 'INACTIVA',
    SALDO DECIMAL(10,2) DEFAULT 0.00,
    FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO)
);

-- Crear tabla de transacciones
CREATE TABLE IF NOT EXISTS transacciones (
    ID_TRANSACCION INT AUTO_INCREMENT PRIMARY KEY,
    ID_TARJETA INT,
    TIPO ENUM('DEPOSITO', 'RETIRO') NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_TARJETA) REFERENCES tarjetas(ID_TARJETA)
); 