-- Modificar la tabla usuarios para agregar los campos necesarios
ALTER TABLE usuarios
ADD COLUMN ID_EMPRESA INT,
ADD COLUMN GENERO VARCHAR(20),
ADD COLUMN FECHA_NACIMIENTO DATE,
ADD COLUMN TELEFONO VARCHAR(20),
ADD COLUMN CODIGO_POSTAL VARCHAR(10),
ADD COLUMN RFC VARCHAR(13),
ADD COLUMN DIRECCION VARCHAR(255),
ADD COLUMN FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD FOREIGN KEY (ID_EMPRESA) REFERENCES empresas(ID_EMPRESA);

-- Renombrar columnas existentes para mantener consistencia
ALTER TABLE usuarios
CHANGE COLUMN ID ID_USUARIO INT AUTO_INCREMENT,
CHANGE COLUMN name NOMBRE VARCHAR(255),
CHANGE COLUMN email EMAIL VARCHAR(255); 